// mt-sigma-algebra widget — bespoke semantic registry entry.
//
//   renderMarkup(params)  -> <div class="widget" id="..."> ... </div>
//   renderScript(params)  -> <script> ... </script>
//
// Pure functions of params. The sigma-algebra generated by a family E on a
// finite X: sigma(E) is exactly the unions of the ATOMS (the partition of X by
// membership pattern across E), so |sigma(E)| = 2^(#atoms).

import { escapeHtml } from '../_shared/escape.mjs';

export function renderMarkup(params) {
  const { widgetId, title, hint } = params;
  const hintHtml = hint ? `<div class="hint">${escapeHtml(hint)}</div>` : '';
  return (
    `<div class="widget" id="${widgetId}">\n` +
    `  <div class="hd"><div class="ttl">${escapeHtml(title)}</div>${hintHtml}</div>\n` +
    `  <div class="row"><span class="note">generators $\\mathcal{E}$ (toggle to add/remove subsets of $X=\\{1,2,3,4\\}$):</span>\n` +
    `    <span id="${widgetId}-bank" style="display:inline-flex;gap:.35rem;flex-wrap:wrap"></span>\n` +
    `  </div>\n` +
    `  <div class="row" id="${widgetId}-presets" role="group" aria-label="preset">\n` +
    `    <button type="button" data-pre="trivial" aria-pressed="false">trivial</button>\n` +
    `    <button type="button" data-pre="one" aria-pressed="false">one event</button>\n` +
    `    <button type="button" data-pre="two" aria-pressed="false">a partition</button>\n` +
    `    <button type="button" data-pre="discrete" aria-pressed="false">discrete</button>\n` +
    `  </div>\n` +
    `  <svg id="${widgetId}-svg" viewBox="0 0 560 320" width="560" height="320" role="img" aria-label="The set X coloured by atom, and the full list of subsets in the generated sigma-algebra"><title>The generated σ-algebra σ(E): X is partitioned into atoms by the generators, and σ(E) is exactly the unions of those atoms</title></svg>\n` +
    `  <div class="readout" id="${widgetId}-out"></div>\n` +
    `</div>`
  );
}

export function renderScript(params) {
  const { widgetId } = params;
  return (
    `<script>\n` +
    `/* mt-sigma-algebra widget: ${widgetId} */\n` +
    `(function(){\n` +
    `  var svg=document.getElementById('${widgetId}-svg'), out=document.getElementById('${widgetId}-out');\n` +
    `  var bank=document.getElementById('${widgetId}-bank'), presets=document.getElementById('${widgetId}-presets');\n` +
    `  if(!svg||!out||!bank||!presets) return;\n` +
    `  var NS='http://www.w3.org/2000/svg';\n` +
    `  function mk(tag,attrs,text){ var e=document.createElementNS(NS,tag); for(var k in attrs){ e.setAttribute(k,attrs[k]); } if(text!=null) e.textContent=text; return e; }\n` +
    `  function txt(x,y,s,opt){ opt=opt||{}; svg.appendChild(mk('text',{x:x,y:y,'text-anchor':opt.anchor||'start','font-size':opt.size||12,fill:opt.fill||'var(--ink)','font-weight':opt.weight||'normal'},s)); }\n` +
    `  var N=4, FULL=(1<<N)-1;\n` +
    `  var BANK=[{m:1,lab:'{1}'},{m:2,lab:'{2}'},{m:3,lab:'{1,2}'},{m:6,lab:'{2,3}'},{m:12,lab:'{3,4}'}];\n` +
    `  var on=[false,false,true,false,false];\n` +  // default: E={ {1,2} }
    `  var ATOMCOL=['var(--cyan)','var(--yellow)','var(--green)','var(--pink)'];\n` +
    `  function fmt(m){ if(m===0) return '\\u2205'; if(m===FULL) return 'X'; var e=[]; for(var i=0;i<N;i++) if(m&(1<<i)) e.push(i+1); return '{'+e.join(',')+'}'; }\n` +
    `  function atoms(){ var gens=BANK.filter(function(b,i){return on[i];}).map(function(b){return b.m;}); var sig={}, order=[]; for(var i=0;i<N;i++){ var s=gens.map(function(g){return (g>>i)&1;}).join(''); if(!(s in sig)){ sig[s]=0; order.push(s); } sig[s]|=(1<<i); } return order.map(function(s){return sig[s];}); }\n` +
    `  function sigma(at){ var k=at.length, out=[]; for(var s=0;s<(1<<k);s++){ var m=0; for(var j=0;j<k;j++) if(s&(1<<j)) m|=at[j]; out.push(m); } out.sort(function(a,b){return a-b;}); return out; }\n` +
    `  function atomOf(i, at){ for(var j=0;j<at.length;j++) if(at[j]&(1<<i)) return j; return 0; }\n` +
    `  function buildBank(){\n` +
    `    bank.innerHTML='';\n` +
    `    BANK.forEach(function(b,i){ var btn=document.createElement('button'); btn.type='button'; var act=on[i];\n` +
    `      btn.style.cssText='padding:.1rem .5rem;border-radius:6px;background:var(--panel2);cursor:pointer;font-size:12px;border:1px solid '+(act?'var(--violet)':'var(--line)')+';color:'+(act?'var(--violet)':'var(--mute)')+';font-weight:'+(act?'700':'400');\n` +
    `      btn.textContent=b.lab; btn.setAttribute('aria-pressed', act?'true':'false'); btn.setAttribute('aria-label','toggle generator '+b.lab);\n` +
    `      btn.addEventListener('click', function(){ on[i]=!on[i]; clearPresets(); buildBank(); draw(); });\n` +
    `      bank.appendChild(btn);\n` +
    `    });\n` +
    `  }\n` +
    `  function draw(){\n` +
    `    while(svg.firstChild) svg.removeChild(svg.firstChild);\n` +
    `    var at=atoms(), sig=sigma(at), k=at.length;\n` +
    `    var genList=BANK.filter(function(b,i){return on[i];}).map(function(b){return b.lab;});\n` +
    // X elements coloured by atom
    `    txt(40, 40, 'X = {1, 2, 3, 4}, coloured by atom:', {size:11, fill:'var(--mute)'});\n` +
    `    for(var i=0;i<N;i++){ var col=ATOMCOL[atomOf(i,at)%ATOMCOL.length]; var x=70+i*64;\n` +
    `      svg.appendChild(mk('circle',{cx:x, cy:72, r:15, fill:col, 'fill-opacity':0.25, stroke:col, 'stroke-width':2}));\n` +
    `      txt(x, 77, ''+(i+1), {size:14, fill:'var(--ink)', weight:600, anchor:'middle'});\n` +
    `    }\n` +
    `    txt(40, 112, 'atoms (the partition E generates): '+at.map(fmt).join('  '), {size:10, fill:'var(--ink)'});\n` +
    // sigma(E) list
    `    txt(40, 140, '\\u03c3(\\u2130) = all unions of atoms:', {size:11, fill:'var(--violet)', weight:600});\n` +
    `    var perCol=8, colW=120, x0=46, y0=160, rh=18;\n` +
    `    sig.forEach(function(m,idx){ var c=Math.floor(idx/perCol), rr=idx%perCol; txt(x0+c*colW, y0+rr*rh, fmt(m), {size:11, fill:'var(--cyan)'}); });\n` +
    // right panel
    `    var TX=400, ty=44;\n` +
    `    txt(TX, ty, '\\u2130 = { '+(genList.join(', ')||'\\u2205')+' }', {size:11, fill:'var(--violet)', weight:600}); ty+=24;\n` +
    `    txt(TX, ty, '#atoms = '+k, {size:11, fill:'var(--mute)'}); ty+=18;\n` +
    `    txt(TX, ty, '|\\u03c3(\\u2130)| = 2^'+k+' = '+sig.length, {size:14, fill:'var(--ink)', weight:700}); ty+=28;\n` +
    // verify the three axioms live on the computed sigma(E) (always hold, by construction)
    `    var setm={}; for(var si=0;si<sig.length;si++) setm[sig[si]]=1;\n` +
    `    var axE=!!setm[0], axC=sig.every(function(m){return setm[(~m)&FULL];}), axU=sig.every(function(a){return sig.every(function(b){return setm[a|b];});});\n` +
    `    function chk(ok){ return ok?'\\u2713':'\\u2717'; } function ccol(ok){ return ok?'var(--green)':'var(--pink)'; }\n` +
    `    txt(TX, ty, 'axioms (verified on \\u03c3(\\u2130)):', {size:10, fill:'var(--mute)'}); ty+=16;\n` +
    `    txt(TX, ty, chk(axE)+' \\u2205 \\u2208 \\u03c3(\\u2130)', {size:10, fill:ccol(axE)}); ty+=15;\n` +
    `    txt(TX, ty, chk(axC)+' closed under complement', {size:10, fill:ccol(axC)}); ty+=15;\n` +
    `    txt(TX, ty, chk(axU)+' closed under union (finite \\u21d2 countable)', {size:10, fill:ccol(axU)}); ty+=24;\n` +
    `    txt(TX, ty, k===1?'trivial \\u03c3-algebra':(sig.length===(1<<N)?'discrete: \\u03c3(\\u2130)=2^X':'generated by \\u2130'), {size:9, fill:'var(--mute)'});\n` +
    `    out.textContent = 'A \\u03c3-algebra on X must contain \\u2205, be closed under complement, and closed under countable unions. The \\u03c3-algebra generated by a family \\u2130, \\u03c3(\\u2130), is the smallest one containing \\u2130. On a FINITE set this has a clean description: two points lie in the same ATOM iff every generator contains both or neither, partitioning X into '+k+' atom'+(k===1?'':'s')+' ('+at.map(fmt).join(', ')+'); then \\u03c3(\\u2130) is exactly the set of all UNIONS of atoms. So |\\u03c3(\\u2130)| = 2^(#atoms) = 2^'+k+' = '+sig.length+'. With \\u2130 = { '+(genList.join(', ')||'\\u2205')+' }: '+(k===1?'no generator separates any points, so the only atom is X and \\u03c3(\\u2130) = {\\u2205, X} is trivial.':(sig.length===(1<<N)?'the generators separate every point, so every singleton is an atom and \\u03c3(\\u2130) = 2^X is the full discrete \\u03c3-algebra (16 subsets).':'the atoms are the indivisible events; every measurable set is a union of them.'))+' Applied to the open sets of \\u211d this construction gives the Borel \\u03c3-algebra; a measure assigns a countably-additive size to each set in \\u03c3(\\u2130).';\n` +
    `  }\n` +
    `  function clearPresets(){ Array.prototype.forEach.call(presets.querySelectorAll('button'), function(x){ x.classList.remove('active'); x.setAttribute('aria-pressed','false'); }); }\n` +
    `  Array.prototype.forEach.call(presets.querySelectorAll('button'), function(b){ b.addEventListener('click', function(){\n` +
    `    var p=b.getAttribute('data-pre');\n` +
    `    if(p==='trivial') on=[false,false,false,false,false];\n` +
    `    else if(p==='one') on=[false,false,true,false,false];\n` +
    `    else if(p==='two') on=[true,false,true,false,false];\n` +
    `    else if(p==='discrete') on=[true,true,false,true,false];\n` +
    `    Array.prototype.forEach.call(presets.querySelectorAll('button'), function(x){ var act=(x===b); x.classList.toggle('active',act); x.setAttribute('aria-pressed', act?'true':'false'); });\n` +
    `    buildBank(); draw();\n` +
    `  }); });\n` +
    `  buildBank(); draw();\n` +
    `})();\n` +
    `</script>`
  );
}
