// AUTO-GENERATED by scripts/build-tours-data.mjs from tours.html — do not edit.
window.MV_TOURS = [
  {
    "id": "bsd-road",
    "title": "The road to BSD",
    "color": "cyan",
    "stops": [
      {
        "page": "elliptic-curves.html",
        "anchor": "group",
        "title": "Elliptic curves and the chord–tangent group law"
      },
      {
        "page": "modular-forms.html",
        "anchor": "forms",
        "title": "Modular forms on the upper half-plane"
      },
      {
        "page": "L-functions.html",
        "anchor": "elliptic",
        "title": "L-functions: $L(E,s)$ and $L(f,s)$"
      },
      {
        "page": "modularity-and-flt.html",
        "anchor": "modularity",
        "title": "Modularity: every elliptic curve over $\\mathbb{Q}$ is a modular form"
      },
      {
        "page": "bsd.html",
        "anchor": "bsd-rank-equality",
        "title": "Birch &amp; Swinnerton-Dyer: analytic rank = algebraic rank"
      }
    ]
  },
  {
    "id": "flt-proof",
    "title": "How Fermat's Last Theorem was proved",
    "color": "yellow",
    "stops": [
      {
        "page": "galois.html",
        "anchor": "solvable",
        "title": "Galois theory and solvable extensions"
      },
      {
        "page": "modular-forms.html",
        "anchor": "forms",
        "title": "Modular forms and newforms of level $N$"
      },
      {
        "page": "modular-curves.html",
        "anchor": "moduli",
        "title": "Modular curves $X_0(N)$ as moduli of elliptic curves"
      },
      {
        "page": "galois-representations.html",
        "anchor": "tate",
        "title": "Galois representations from the Tate module"
      },
      {
        "page": "modularity-and-flt.html",
        "anchor": "ribet",
        "title": "Ribet + Wiles ⇒ FLT"
      }
    ]
  },
  {
    "id": "cohomology",
    "title": "What is cohomology?",
    "color": "violet",
    "stops": [
      {
        "page": "group-cohomology.html",
        "anchor": "h2",
        "title": "Group cohomology and $H^2$ as central extensions"
      },
      {
        "page": "algebraic-topology.html",
        "anchor": "homology",
        "title": "Singular homology and cohomology of a space"
      },
      {
        "page": "sheaf-cohomology.html",
        "anchor": "cech",
        "title": "Sheaf cohomology via Čech and derived functors"
      },
      {
        "page": "algebraic-de-rham-cohomology.html",
        "anchor": "comparison-betti",
        "title": "Algebraic de Rham cohomology and the Hodge filtration"
      },
      {
        "page": "etale-cohomology.html",
        "anchor": "weil",
        "title": "Étale cohomology and the Weil conjectures"
      }
    ]
  },
  {
    "id": "sets-to-topoi",
    "title": "From naive sets to ∞-topoi",
    "color": "green",
    "stops": [
      {
        "page": "naive-set-theory.html",
        "anchor": "sets",
        "title": "Sets, functions, products, and equivalence relations"
      },
      {
        "page": "category-theory.html",
        "anchor": "yoneda",
        "title": "Categories, functors, Yoneda"
      },
      {
        "page": "elementary-topos-theory.html",
        "anchor": "subobject-classifier",
        "title": "Elementary toposes and the subobject classifier"
      },
      {
        "page": "simplicial-sets-and-nerve.html",
        "anchor": "nerve-of-category",
        "title": "Simplicial sets and the nerve of a category"
      },
      {
        "page": "infinity-categories.html",
        "anchor": "quasi-category",
        "title": "$\\infty$-categories as quasi-categories"
      },
      {
        "page": "infinity-topoi.html",
        "anchor": "infty-topos-definition",
        "title": "$\\infty$-topoi and Lurie's higher topos theory"
      }
    ]
  },
  {
    "id": "sound-to-wavelets",
    "title": "From sound to wavelets",
    "color": "pink",
    "stops": [
      {
        "page": "harmonic-analysis-fourier.html",
        "anchor": "fourier-transform",
        "title": "Fourier series and the Fourier transform"
      },
      {
        "page": "sobolev-spaces-distributions.html",
        "anchor": "weak-derivative",
        "title": "Distributions and weak derivatives"
      },
      {
        "page": "spectral-theory.html",
        "anchor": "self-adjoint",
        "title": "Spectral theory of self-adjoint operators"
      },
      {
        "page": "wavelets.html",
        "anchor": "multiresolution",
        "title": "Wavelets and multiresolution analysis"
      }
    ]
  },
  {
    "id": "local-global",
    "title": "The local–global principle",
    "color": "blue",
    "stops": [
      {
        "page": "algebraic-number-theory.html",
        "anchor": "dedekind",
        "title": "Number fields, rings of integers, Dedekind domains"
      },
      {
        "page": "p-adic-numbers.html",
        "anchor": "qp",
        "title": "$p$-adic numbers and Hensel's lemma"
      },
      {
        "page": "adeles-and-ideles.html",
        "anchor": "adeles",
        "title": "Adèles and idèles: all places at once"
      },
      {
        "page": "frobenius-and-reciprocity.html",
        "anchor": "frobenius",
        "title": "Frobenius elements and Chebotarev density"
      },
      {
        "page": "heights-arithmetic-geometry.html",
        "anchor": "canonical",
        "title": "Heights, Northcott, and the canonical height"
      }
    ]
  },
  {
    "id": "solvability-arc",
    "title": "Solvability across mathematics",
    "color": "violet",
    "stops": [
      {
        "page": "galois.html",
        "anchor": "quintic",
        "title": "Galois solvability and why the quintic resists radicals"
      },
      {
        "page": "group-cohomology.html",
        "anchor": "h2",
        "title": "Group cohomology: $H^2$ classifies central extensions"
      },
      {
        "page": "algebraic-topology.html",
        "anchor": "homology",
        "title": "Singular homology and the chain-complex pattern"
      },
      {
        "page": "infinity-categories.html",
        "anchor": "quasi-category",
        "title": "∞-categories: spaces ARE ∞-groupoids"
      },
      {
        "page": "motives.html",
        "anchor": "motivic-galois",
        "title": "Motives: the universal Galois group of cohomology"
      }
    ]
  },
  {
    "id": "hodge-arc",
    "title": "What is Hodge theory?",
    "color": "green",
    "stops": [
      {
        "page": "complex-analysis.html",
        "anchor": "holomorphic-function",
        "title": "Holomorphic functions and the Cauchy–Riemann equations"
      },
      {
        "page": "algebraic-de-rham-cohomology.html",
        "anchor": "de-rham-complex",
        "title": "The de Rham complex $\\Omega^\\bullet_{X/k}$ and its hypercohomology"
      },
      {
        "page": "hodge-theory.html",
        "anchor": "decomposition",
        "title": "The Hodge decomposition theorem"
      },
      {
        "page": "hodge-theory.html",
        "anchor": "mixed-hodge",
        "title": "Mixed Hodge structures (Deligne)"
      },
      {
        "page": "hodge-theory.html",
        "anchor": "hodge-conjecture",
        "title": "The Hodge conjecture"
      }
    ]
  },
  {
    "id": "langlands-arc",
    "title": "Langlands philosophy",
    "color": "cyan",
    "stops": [
      {
        "page": "galois-representations.html",
        "anchor": "rep",
        "title": "Galois representations"
      },
      {
        "page": "modular-forms.html",
        "anchor": "forms",
        "title": "Modular forms and Hecke eigenforms"
      },
      {
        "page": "L-functions.html",
        "anchor": "unified",
        "title": "L-functions: Euler products and functional equations"
      },
      {
        "page": "class-field-theory.html",
        "anchor": "artin",
        "title": "Class field theory: Langlands for $\\GL_1$"
      },
      {
        "page": "langlands-program.html",
        "anchor": "capstone",
        "title": "The Langlands program — universal reciprocity"
      }
    ]
  },
  {
    "id": "millennium-prizes",
    "title": "The seven Millennium Prize Problems",
    "color": "orange",
    "stops": [
      {
        "page": "L-functions.html",
        "anchor": "zeta",
        "title": "Riemann Hypothesis"
      },
      {
        "page": "complexity-theory.html",
        "anchor": "",
        "title": "P versus NP"
      },
      {
        "page": "hodge-theory.html",
        "anchor": "hodge-conjecture",
        "title": "Hodge Conjecture"
      },
      {
        "page": "gauge-theory.html",
        "anchor": "",
        "title": "Yang–Mills existence and mass gap"
      },
      {
        "page": "partial-differential-equations.html",
        "anchor": "",
        "title": "Navier–Stokes existence and smoothness"
      },
      {
        "page": "bsd.html",
        "anchor": "",
        "title": "Birch and Swinnerton-Dyer"
      },
      {
        "page": "ricci-flow.html",
        "anchor": "poincare",
        "title": "Poincaré Conjecture"
      }
    ]
  },
  {
    "id": "sato-tate",
    "title": "Sato–Tate: semicircles from elliptic curves",
    "color": "cyan",
    "stops": [
      {
        "page": "elliptic-curves.html",
        "anchor": "group",
        "title": "Elliptic curves and Frobenius traces $a_p(E)$"
      },
      {
        "page": "sato-tate.html",
        "anchor": "measure",
        "title": "The Sato–Tate distribution $\\tfrac{2}{\\pi}\\sin^2\\theta\\,d\\theta$"
      },
      {
        "page": "L-functions.html",
        "anchor": "modularity",
        "title": "L-functions of symmetric powers"
      },
      {
        "page": "modularity-and-flt.html",
        "anchor": "modularity",
        "title": "Modularity and potential modularity"
      },
      {
        "page": "sato-tate.html",
        "anchor": "coda",
        "title": "The Sato–Tate theorem"
      }
    ]
  }
];
