#!/usr/bin/env node
// Scaffold a new concept inside an existing topic.
//
// Usage:
//   node scripts/new-concept.mjs <topic-slug> <concept-id> \
//     [--title "Human title"] [--anchor short-name]
//
// Without scaffolding, adding a concept means hand-editing 4 files:
//   - concepts/<topic>.json    append to `concepts[]`
//   - quizzes/<topic>.json     append a stub bank under the concept id
//   - content/<topic>.json     insert a new section (raw + quiz blocks)
//   - <topic>.html             regenerated by rebuild from content/json
//
// This script does the first three; the rebuild handles HTML rendering.
//
// Soft-fail: validates existence + non-duplicate before any write.
//
// Zero dependencies.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const repoRoot = resolve(dirname(__filename), '..');

// ----- Args -----
const argv = process.argv.slice(2);
function flagValue(name) {
  const i = argv.indexOf(name);
  if (i === -1) return null;
  return argv[i + 1] ?? null;
}
const positional = argv.filter((a, i) => {
  if (a.startsWith('--')) return false;
  if (i > 0 && argv[i - 1]?.startsWith('--')) return false;
  return true;
});
const [topicSlug, conceptId] = positional;
if (!topicSlug || !conceptId) {
  console.error('usage: node scripts/new-concept.mjs <topic-slug> <concept-id> [--title T] [--anchor A]');
  process.exit(2);
}
if (!/^[a-z][a-z0-9-]*$/.test(conceptId)) {
  console.error(`new-concept: concept-id "${conceptId}" must be kebab-case (a-z, 0-9, dashes)`);
  process.exit(1);
}

const titleArg = flagValue('--title');
const anchorArg = flagValue('--anchor');

// Default title: "concept-id" → "Concept id"
const humanTitle =
  titleArg ??
  conceptId.replace(/-/g, ' ').replace(/^./, (c) => c.toUpperCase());

// Default anchor: strip topic-stem prefix if any (e.g., "la-foo" → "foo"
// when other concepts in the topic share that prefix). Otherwise, use the
// concept-id verbatim. The convention in this repo is short anchors; the
// user can override with --anchor.
function detectTopicPrefix(existingConcepts) {
  const ids = existingConcepts.map((c) => c.id).filter(Boolean);
  if (ids.length === 0) return null;
  const first = ids[0];
  const dash = first.indexOf('-');
  if (dash === -1) return null;
  const prefix = first.slice(0, dash + 1);
  if (ids.every((id) => id.startsWith(prefix))) return prefix;
  return null;
}

// ----- Validate target files -----
const conceptPath = join(repoRoot, 'concepts', `${topicSlug}.json`);
const contentPath = join(repoRoot, 'content', `${topicSlug}.json`);
const quizPath = join(repoRoot, 'quizzes', `${topicSlug}.json`);

for (const [path, label] of [
  [conceptPath, 'concepts'],
  [contentPath, 'content'],
  [quizPath, 'quizzes'],
]) {
  if (!existsSync(path)) {
    console.error(`new-concept: ${label}/${topicSlug}.json not found — is "${topicSlug}" registered?`);
    process.exit(1);
  }
}

const conceptDoc = JSON.parse(readFileSync(conceptPath, 'utf8'));
const contentDoc = JSON.parse(readFileSync(contentPath, 'utf8'));
const quizDoc = JSON.parse(readFileSync(quizPath, 'utf8'));

if ((conceptDoc.concepts || []).some((c) => c.id === conceptId)) {
  console.error(`new-concept: concept "${conceptId}" already exists in concepts/${topicSlug}.json`);
  process.exit(1);
}

const topicPrefix = detectTopicPrefix(conceptDoc.concepts || []);
const anchor =
  anchorArg ??
  (topicPrefix && conceptId.startsWith(topicPrefix)
    ? conceptId.slice(topicPrefix.length)
    : conceptId);

if ((contentDoc.sections || []).some((s) => s.id === anchor)) {
  console.error(`new-concept: section anchor "${anchor}" already exists in content/${topicSlug}.json — pass --anchor to disambiguate`);
  process.exit(1);
}

// ----- Build stubs -----

// concepts/<topic>.json append.
const newConceptEntry = {
  id: conceptId,
  title: humanTitle,
  anchor,
  prereqs: [],
  blurb: 'TODO: 1–2 sentences explaining the concept and its essential payoff.',
};
conceptDoc.concepts.push(newConceptEntry);

// quizzes/<topic>.json append.
quizDoc.quizzes ??= {};
quizDoc.quizzes[conceptId] = {
  title: humanTitle,
  questions: [
    {
      type: 'mcq',
      q: 'TODO: question stem.',
      choices: ['option A', 'option B', 'option C', 'option D'],
      answer: 0,
      explain: 'TODO: 1–2 sentences explaining why the right choice is right.',
      hint: 'TODO: a nudge that does not give away the answer.',
    },
  ],
};

// content/<topic>.json append a new section.
const sectionNumber = (contentDoc.sections || []).length + 1;
const openHtml =
  `<section id="${anchor}">\n` +
  `<h2>${sectionNumber}. ${humanTitle}</h2>\n` +
  `<p>TODO: prose for ${conceptId}. Replace this paragraph with the worked development of the concept.</p>\n\n`;
const closeHtml = `\n</section>\n\n`;
const quizPlaceholder = `<div class="quiz" data-concept="${conceptId}"></div>`;

contentDoc.sections ??= [];
contentDoc.sections.push({
  id: anchor,
  blocks: [
    { type: 'raw', html: openHtml },
    { type: 'quiz', concept: conceptId, html: quizPlaceholder },
    { type: 'raw', html: closeHtml },
  ],
});

// ----- Write -----
writeFileSync(conceptPath, JSON.stringify(conceptDoc, null, 2) + '\n');
writeFileSync(contentPath, JSON.stringify(contentDoc, null, 2) + '\n');
writeFileSync(quizPath, JSON.stringify(quizDoc, null, 2) + '\n');

console.log(`new-concept: scaffolded "${conceptId}" in topic "${topicSlug}".`);
console.log('  wrote:');
console.log(`    concepts/${topicSlug}.json    (appended concept "${conceptId}")`);
console.log(`    quizzes/${topicSlug}.json     (stub bank under "${conceptId}")`);
console.log(`    content/${topicSlug}.json     (new section #${anchor}, position ${sectionNumber})`);
console.log('');
console.log('Next steps:');
console.log(`  1. Edit content/${topicSlug}.json — replace the TODO prose in the new section.`);
console.log(`     Add widget blocks (registry slug + params) or inline widgets as appropriate.`);
console.log(`  2. Set the concept's prereqs[] in concepts/${topicSlug}.json.`);
console.log(`  3. Replace the stub mcq in quizzes/${topicSlug}.json with real v1 questions.`);
console.log(`  4. Run: node scripts/rebuild.mjs`);
console.log(`     (renders HTML from content JSON, rebuilds bundles, validates the graph.)`);
