// langlands-cft-gl1 widget — bespoke semantic registry entry.
//
//   renderMarkup(params)  -> <div class="widget" id="..."> ... </div>
//   renderScript(params)  -> <script> ... </script>
//
// Pure functions of params. The GL_1 case of Langlands = class field theory,
// made concrete on cyclotomic fields: Gal(Q(zeta_N)/Q) = (Z/N)^x, the Artin
// reciprocity map sends a prime p to Frob_p = (p mod N), Dirichlet characters
// mod N ARE the 1-dim Galois characters, and the order-2 ones cut out the
// quadratic subfields. Frobenius computed live by modular arithmetic.
// Plain Q / Z / F (blackboard is astral); zeta/phi/chi are BMP Greek.

import { escapeHtml } from '../_shared/escape.mjs';

export function renderMarkup(params) {
  const { widgetId, title, hint } = params;
  const hintHtml = hint ? `<div class="hint">${escapeHtml(hint)}</div>` : '';
  const nbtn = (k, lab, on) =>
    `<button type="button" data-n="${k}" class="${on ? 'active' : ''}" aria-pressed="${on ? 'true' : 'false'}">${lab}</button>`;
  const cbtn = (k) =>
    `<button type="button" data-c="${k}" class="${k === 0 ? 'active' : ''}" aria-pressed="${k === 0 ? 'true' : 'false'}">&#967;<sub>${k}</sub></button>`;
  return (
    `<div class="widget" id="${widgetId}">\n` +
    `  <div class="hd"><div class="ttl">${escapeHtml(title)}</div>${hintHtml}</div>\n` +
    `  <div class="row" id="${widgetId}-nbtns">\n` +
    `    <label>N =</label>\n    ${nbtn('5', '5', true)}\n    ${nbtn('8', '8', false)}\n    ${nbtn('12', '12', false)}\n` +
    `  </div>\n` +
    `  <div class="row" id="${widgetId}-cbtns">\n` +
    `    <label>character &#967; mod N:</label>\n    ${cbtn(0)}\n    ${cbtn(1)}\n    ${cbtn(2)}\n    ${cbtn(3)}\n` +
    `  </div>\n` +
    `  <svg id="${widgetId}-svg" viewBox="0 0 620 444" width="620" height="444" role="img" aria-label="The cyclotomic case of class field theory: Frobenius at a prime p equals p mod N inside the Galois group, and a chosen Dirichlet character evaluated at Frobenius tells how p splits."><title>For the cyclotomic field generated by an N-th root of unity, the Galois group over the rationals is the unit group mod N, and the Artin reciprocity map sends each prime p not dividing N to its Frobenius, equal to p mod N. The widget tabulates Frobenius, the residue degree, and the value of a chosen Dirichlet character at Frobenius for the first several primes; the order-two characters cut out the quadratic subfields, and a character value of plus one means the prime splits in that subfield.</title></svg>\n` +
    `  <div class="readout" id="${widgetId}-out"></div>\n` +
    `</div>`
  );
}

export function renderScript(params) {
  const { widgetId } = params;
  return (
    `<script>\n` +
    `/* langlands-cft-gl1 widget: ${widgetId} */\n` +
    `(function(){\n` +
    `  var svg=document.getElementById('${widgetId}-svg'), out=document.getElementById('${widgetId}-out');\n` +
    `  var nbtns=document.getElementById('${widgetId}-nbtns'), cbtns=document.getElementById('${widgetId}-cbtns');\n` +
    `  if(!svg||!out||!nbtns||!cbtns) return;\n` +
    `  var NS='http://www.w3.org/2000/svg';\n` +
    `  function mk(tag,attrs,text){ var e=document.createElementNS(NS,tag); for(var k in attrs){ e.setAttribute(k,attrs[k]); } if(text!=null) e.textContent=text; return e; }\n` +
    `  function txt(x,y,s,opt){ opt=opt||{}; svg.appendChild(mk('text',{x:x,y:y,'text-anchor':opt.anchor||'middle','font-size':opt.size||12,fill:opt.fill||'var(--ink)','font-weight':opt.weight||'normal','font-family':opt.mono?'monospace':'inherit'},s)); }\n` +
    `  // Each character carries a per-residue value LABEL and the subfield it cuts out (kernel fixed field).\n` +
    `  var DATA={\n` +
    `    5:{ struct:'\\u27e82\\u27e9 \\u2245 \\u2124/4 (cyclic)', elts:[1,2,3,4], phi:4,\n` +
    `        chars:[\n` +
    `          {lab:'\\u03c7\\u2080 principal', field:'\\u211a itself (the \\u03b6-function)', quad:false, val:{1:'+1',2:'+1',3:'+1',4:'+1'}},\n` +
    `          {lab:'\\u03c7 (order 4)', field:'\\u211a(\\u03b6\\u2085), order 4 \\u2014 complex', quad:false, val:{1:'1',2:'i',4:'\\u22121',3:'\\u2212i'}},\n` +
    `          {lab:'\\u03c7\\u00b2 = (\\u00b7/5)', field:'\\u211a(\\u221a5)', quad:true, val:{1:'+1',2:'\\u22121',3:'\\u22121',4:'+1'}},\n` +
    `          {lab:'\\u03c7\\u00b3 (order 4)', field:'\\u211a(\\u03b6\\u2085), order 4 \\u2014 complex', quad:false, val:{1:'1',2:'\\u2212i',4:'\\u22121',3:'i'}}\n` +
    `        ]},\n` +
    `    8:{ struct:'{1,3,5,7} \\u2245 \\u2124/2 \\u00d7 \\u2124/2', elts:[1,3,5,7], phi:4,\n` +
    `        chars:[\n` +
    `          {lab:'\\u03c7\\u2080 principal', field:'\\u211a itself', quad:false, val:{1:'+1',3:'+1',5:'+1',7:'+1'}},\n` +
    `          {lab:'\\u03c7 \\u2192 \\u211a(i)', field:'\\u211a(i)', quad:true, val:{1:'+1',3:'\\u22121',5:'+1',7:'\\u22121'}},\n` +
    `          {lab:'\\u03c7 \\u2192 \\u211a(\\u221a2)', field:'\\u211a(\\u221a2)', quad:true, val:{1:'+1',3:'\\u22121',5:'\\u22121',7:'+1'}},\n` +
    `          {lab:'\\u03c7 \\u2192 \\u211a(\\u221a\\u22122)', field:'\\u211a(\\u221a\\u22122)', quad:true, val:{1:'+1',3:'+1',5:'\\u22121',7:'\\u22121'}}\n` +
    `        ]},\n` +
    `    12:{ struct:'{1,5,7,11} \\u2245 \\u2124/2 \\u00d7 \\u2124/2', elts:[1,5,7,11], phi:4,\n` +
    `        chars:[\n` +
    `          {lab:'\\u03c7\\u2080 principal', field:'\\u211a itself', quad:false, val:{1:'+1',5:'+1',7:'+1',11:'+1'}},\n` +
    `          {lab:'\\u03c7 \\u2192 \\u211a(i)', field:'\\u211a(i)', quad:true, val:{1:'+1',5:'+1',7:'\\u22121',11:'\\u22121'}},\n` +
    `          {lab:'\\u03c7 \\u2192 \\u211a(\\u221a\\u22123)', field:'\\u211a(\\u221a\\u22123)', quad:true, val:{1:'+1',5:'\\u22121',7:'+1',11:'\\u22121'}},\n` +
    `          {lab:'\\u03c7 \\u2192 \\u211a(\\u221a3)', field:'\\u211a(\\u221a3)', quad:true, val:{1:'+1',5:'\\u22121',7:'\\u22121',11:'+1'}}\n` +
    `        ]}\n` +
    `  };\n` +
    `  var PRIMES=[2,3,5,7,11,13,17,19,23,29];\n` +
    `  function ord(a,N){ a=a%N; if(a===0) return 0; var k=1, x=a; while(x!==1){ x=(x*a)%N; k++; if(k>N) return 0; } return k; }\n` +
    `  var curN=5, curC=0;\n` +
    `  function relabelChars(){ var D=DATA[curN]; Array.prototype.forEach.call(cbtns.querySelectorAll('button'), function(b){ var k=+b.getAttribute('data-c'); b.textContent=D.chars[k].lab; var on=(k===curC); b.classList.toggle('active',on); b.setAttribute('aria-pressed', on?'true':'false'); }); }\n` +
    `  function draw(){\n` +
    `    while(svg.firstChild) svg.removeChild(svg.firstChild);\n` +
    `    var D=DATA[curN], ch=D.chars[curC];\n` +
    `    svg.setAttribute('aria-label','Cyclotomic class field theory for N='+curN+': Frob_p = p mod '+curN+' in (Z/'+curN+')-units, with the character '+ch.field+'; a value +1 means p splits in that subfield.');\n` +
    `    txt(310,20,'\\u211a(\\u03b6_'+curN+') / \\u211a   \\u2014   the GL\\u2081 (abelian) prototype of Langlands',{size:12.5,weight:700,fill:'var(--violet)'});\n` +
    `    txt(310,40,'Gal(\\u211a(\\u03b6_'+curN+')/\\u211a)  \\u2245  (\\u2124/'+curN+')*  =  {'+D.elts.join(', ')+'}      '+D.struct+',   degree \\u03c6('+curN+') = '+D.phi,{size:11,fill:'var(--cyan)'});\n` +
    `    txt(310,58,'selected character \\u03c7:  '+ch.field,{size:11,fill:'var(--pink)',weight:600});\n` +
    `    txt(310,78,'Artin reciprocity:   prime p   \\u21a6   Frob_p = (p mod '+curN+')  \\u2208  Gal      (\\u03c7 is then a 1-dim Galois rep: \\u03c7(Frob_p) = \\u03c7(p))',{size:10.5,fill:'var(--mute)'});\n` +
    `    var cols=[{x:64,h:'p'},{x:200,h:'Frob_p = p mod '+curN},{x:332,h:'deg f = ord'},{x:432,h:'# primes g'},{x:548,h:'\\u03c7(Frob_p)'}];\n` +
    `    var y0=96;\n` +
    `    cols.forEach(function(c){ txt(c.x,y0+14,c.h,{size: c.h.length>9?9.5:11,weight:700,fill:'var(--violet)'}); });\n` +
    `    svg.appendChild(mk('line',{x1:24,y1:y0+22,x2:596,y2:y0+22,stroke:'var(--line)','stroke-width':0.8}));\n` +
    `    var ry=y0+22;\n` +
    `    PRIMES.forEach(function(p){ if(curN%p===0) return; /* p | N: ramified, excluded */ ry+=27;\n` +
    `      var fr=p%curN, f=ord(p,curN), g=D.phi/f, cv=ch.val[fr], split=(fr===1);\n` +
    `      if(split){ svg.appendChild(mk('rect',{x:24,y:ry-14,width:572,height:25,rx:4,fill:'var(--green)','fill-opacity':0.10})); }\n` +
    `      txt(cols[0].x,ry+4,''+p,{size:11.5,mono:true});\n` +
    `      txt(cols[1].x,ry+4,''+fr+(split?'  (\\u2261 1: splits completely)':''),{size:11,mono:true,fill: split?'var(--green)':'var(--cyan)'});\n` +
    `      txt(cols[2].x,ry+4,''+f,{size:11,mono:true});\n` +
    `      txt(cols[3].x,ry+4,''+g,{size:11,mono:true});\n` +
    `      var cvcol = (cv==='+1')?'var(--green)':((cv==='\\u22121')?'var(--pink)':'var(--yellow)');\n` +
    `      txt(cols[4].x,ry+4,cv,{size:12,mono:true,weight:700,fill:cvcol});\n` +
    `      svg.appendChild(mk('line',{x1:24,y1:ry+13,x2:596,y2:ry+13,stroke:'var(--line)','stroke-width':0.35}));\n` +
    `    });\n` +
    `    ry+=30;\n` +
    `    if(ch.quad){ txt(310,ry,'\\u03c7 has order 2: its kernel fixes the quadratic subfield '+ch.field+'   \\u2014   \\u03c7(p) = +1 \\u21d4 p splits in '+ch.field+',  \\u22121 \\u21d4 inert',{size:10,fill:'var(--mute)'}); }\n` +
    `    else if(curC===0){ txt(310,ry,'principal \\u03c7: every \\u03c7(p) = +1; its L-function is the Riemann \\u03b6 (the trivial 1-dim rep)',{size:10,fill:'var(--mute)'}); }\n` +
    `    else { txt(310,ry,'\\u03c7 has order 4 (genuinely complex): it does not factor through a quadratic field \\u2014 it sees all of \\u211a(\\u03b6\\u2085)',{size:10,fill:'var(--mute)'}); }\n` +
    `    txt(310,ry+22,'Class field theory  =  Langlands for GL\\u2081      \\u00b7      L(\\u03c7, s) = L(\\u03c7^{Hecke}, s)      (Artin, 1920s)',{size:11,weight:700,fill:'var(--yellow)'});\n` +
    `    out.textContent = 'GL\\u2081 LANGLANDS IS CLASS FIELD THEORY \\u2014 the fully-proven abelian prototype. The cyclotomic character identifies Gal(\\u211a(\\u03b6_'+curN+')/\\u211a) with (\\u2124/'+curN+')* canonically, and ARTIN RECIPROCITY is the statement that the Frobenius at an unramified prime p (i.e. p \\u2224 '+curN+') is just Frob_p = (p mod '+curN+') sitting in that group. So the splitting of p is read off by reducing mod '+curN+': p splits completely in \\u211a(\\u03b6_'+curN+') exactly when p \\u2261 1 (mod '+curN+'), and its residue degree f is the multiplicative order of (p mod '+curN+'), with g = \\u03c6('+curN+')/f primes lying above. The four DIRICHLET CHARACTERS mod '+curN+' ARE the characters of this abelian Galois group \\u2014 equivalently the 1-dimensional Galois representations \\u03c1: Gal \\u2192 \\u2102* \\u2014 and \\u03c7(Frob_p) = \\u03c7(p). The order-2 characters factor through the QUADRATIC SUBFIELDS of \\u211a(\\u03b6_'+curN+') ('+D.chars.filter(function(c){return c.quad;}).map(function(c){return c.field;}).join(', ')+'), and \\u03c7(p) = +1 precisely when p splits in that subfield \\u2014 quadratic reciprocity wearing its CFT clothes. In the full adelic statement, Gal(\\u211a-bar/\\u211a)^{ab} is isomorphic to the character group of the id\\u00e8le class group A_\\u211a^\\u00d7/\\u211a^\\u00d7 (A = the ad\\u00e8les), a Dirichlet character matches a HECKE character, and the Artin L-function equals the Hecke (Dirichlet) L-function \\u2014 the n=1 case of L(\\u03c1,s) = L(\\u03c0,s). Artin proved all of this in the 1920s, long before \\u201cLanglands\\u201d had a name.';\n` +
    `  }\n` +
    `  nbtns.addEventListener('click', function(e){ var b=e.target.closest('button'); if(!b||!b.getAttribute('data-n')) return; curN=+b.getAttribute('data-n'); if(curC>=DATA[curN].chars.length) curC=0;\n` +
    `    Array.prototype.forEach.call(nbtns.querySelectorAll('button'), function(x){ var on=x===b; x.classList.toggle('active',on); x.setAttribute('aria-pressed', on?'true':'false'); });\n` +
    `    relabelChars(); draw(); });\n` +
    `  cbtns.addEventListener('click', function(e){ var b=e.target.closest('button'); if(!b||b.getAttribute('data-c')==null) return; curC=+b.getAttribute('data-c');\n` +
    `    Array.prototype.forEach.call(cbtns.querySelectorAll('button'), function(x){ var on=x===b; x.classList.toggle('active',on); x.setAttribute('aria-pressed', on?'true':'false'); });\n` +
    `    draw(); });\n` +
    `  relabelChars(); draw();\n` +
    `})();\n` +
    `</script>`
  );
}
